### ISSUE TITLE
Wordpress multisite

### ISSUE THREAD

**Issue by antic1pate** [motionpage/motion.page#3]
The plugin doesn't open on multisite installation. Blank screen.

**Comment by Rados51** [comment]
Hi @antic1pate, motion.page will not work for multisite right now, but we will try to integrate it soon.

**Comment by pixluser** [comment]
That would be awesome!

**Comment by Rados51** [comment]
@antic1pate @pixluser This is fixed (and tested) in the upcoming version 💯
