### ISSUE TITLE
Animation selector (selector detector) triggers JS actions on page instead of intended use

### ISSUE THREAD

**Issue by wdaellenbach** [motionpage/motion.page#5]
When using the animation selector, elements that have click functions bound to them will fire instead of the motion.page selector detector interface.  Ex. clicking on button to select for animations tiggers modal opening blocking interface

**Comment by wdaellenbach** [comment]
Also would be nice to add combination selectors with the detector, such as selecting a child class element with parent ID
( with a small checkbox or button to confirm selection(s) )

**Comment by Rados51** [comment]
@wdaellenbach Hi, every click event is disabled inside the iframe, but if the click is triggered by an external JS code (not document event), it's hard to disable that. We will look into it :)

As for the selectors combination , we will add that in the future.

Thanks!

**Comment by Rados51** [comment]
@wdaellenbach Hi, was the issue with JetEngine? If it was, this should be fixed in the upcoming version 💯
