### ISSUE TITLE
violation of the GPL

### ISSUE THREAD

**Issue by manythrough** [motionpage/motion.page#7]
your EULA violates the GPL. especially the section "Intellectual Property and Ownership". also your restriction to apply the GPL only to php files sounds dubious.

**Comment by max-05** [comment]
i don't think they care about this

**Comment by Rados51** [comment]
@manythrough @max-05

We do care about licensing and everything is licensed properly as it should be.
All files are in accordance with its licensing.
PHP files are the only thing that has any ties to code from WordPress core, which is under GPL license itself.
All other files are NOT derivative work, and thus they have their own licensing.

GreenSock files have their own licensing.
Libraries have their own licensing (each license is correctly included in the plugin), which is a mix of:
```
Apache-2.0
Apache-2.0 WITH LLVM-exception
BSD-2-Claus
BSD-3-Clause
MIT
ISC
0BSD
BSD-3-Clause-Clear
```
