### ISSUE TITLE
Font Color not working with Headlines in Elementor

### ISSUE THREAD

**Issue by meisterleise** [motionpage/motion.page#9]
You can give the elementor widget "Headline" a class or an ID, but the option "font color" of motion.page does not work. It only works with the normal text editor widget.

**Comment by Rados51** [comment]
Hi @meisterleise, I think this is the issue with Elementor as it wraps elements in additional divs.
You might need to target an element like `#my-id > div > div` or similar (depends on how the final element is wrapped).
